initial git hooks setup

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,15 +1,33 @@
 #!/bin/sh
 #
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
+# This pre-commit hook that
+#	- test the documentation has no spelling errors.
+#	- test the documentation builds correctly.
+# It can be disabled by using the "-n" option with "git commit".
 #
-# To enable this hook, rename this file to "pre-commit".
+# See http://git-scm.com/book/en/Customizing-Git-Git-Hooks for details.
 
-echo $(pwd)
+# get current working dir. expected same as project root
+CWD=$(pwd)
 
-exit 1
+# change directory into docs dir
+cd ./docs
+echo "Hang on a minute... checking documentation for spelling errors..."
+SPELL_LOG="spell_error.log"
+# Do a spell check on docs
+sphinx-build -E -q -w $SPELL_LOG -b spelling . _build 2> /dev/null
+if test -s $SPELL_LOG; then  # if errors.log exists and isn't empty, then there's some errors
+    echo "[error]  Blocking commit, found spelling errors in documentation:"
+    cat $SPELL_LOG
+    rm -f $SPELL_LOG
+    exit 1
+else
+    echo "[success] Documentation spell check passed without error."
+fi
+rm -f $SPELL_LOG
+# restore current working directory
+cd $CWD
+
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
